from enum import Enum

class Stage(str, Enum):
    NEW_TOPIC = "NEW_TOPIC"
    INGEST_PAPERS = "INGEST_PAPERS"
    BUILD_PAPER_CARDS = "BUILD_PAPER_CARDS"
    MAP_GAPS = "MAP_GAPS"
    HUMAN_SELECT = "HUMAN_SELECT"
    FREEZE_TOPIC = "FREEZE_TOPIC"
    FREEZE_SPEC = "FREEZE_SPEC"
    REPRO_BASELINES = "REPRO_BASELINES"
    IMPLEMENT_IDEA = "IMPLEMENT_IDEA"
    RUN_EXPERIMENTS = "RUN_EXPERIMENTS"
    AUDIT_RESULTS = "AUDIT_RESULTS"
    FREEZE_RESULTS = "FREEZE_RESULTS"
    WRITE_DRAFT = "WRITE_DRAFT"
    REVIEW_DRAFT = "REVIEW_DRAFT"
    STYLE_PASS = "STYLE_PASS"
    SUBMISSION_READY = "SUBMISSION_READY"